[package]
name = "slurmtail"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.40"
jiff = "0.2.15"

[dev-dependencies]
tempfile = "3.20.0"

[[test]]
name = "integration_tests"
path = "tests/integration_tests.rs"
